# Usar uma imagem base do PostgreSQL
FROM postgres:13

# Definir variáveis de ambiente para o banco de dados
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=database

# Expor a porta 5432 para o banco de dados
EXPOSE 5432

