name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Front-End Docker image
        run: |
          docker build -t my-app-frontend ./frontend
          docker tag my-app-frontend mydockerhubusername/my-app-frontend:latest
          docker push mydockerhubusername/my-app-frontend:latest

      - name: Push Back-End Docker image
        run: |
          docker build -t my-app-backend ./backend
          docker tag my-app-backend mydockerhubusername/my-app-backend:latest
          docker push mydockerhubusername/my-app-backend:latest

      - name: Push Database Docker image
        run: |
          docker build -t my-app-database ./database
          docker tag my-app-database mydockerhubusername/my-app-database:latest
          docker push mydockerhubusername/my-app-database:latest

      - name: Simulate Production Deployment
        run: echo "Deploying to production environment (simulation)"

